remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Wildlife Identification in Urban Environments 
description: An image classification API that classifies 15 different types of wildlife around the world

author:
  name: Arafat Hossen